const UserRouter = require('./UserRouter')
const ProductRouter = require('./ProductRouter')
const TypeRouter = require('./TypeRouter')
const BillRouter = require('./BillRouter')
const CartRouter = require('./CartRouter')
const WishlistRouter = require('./WishlistRouter')
const ServiceRouter = require('./ServiceRouter')
const PetRouter = require('./PetRouter')
const AppointmentRouter = require('./AppointmentRouter')
const CouponRouter = require('./CouponRouter')
const ReviewRouter = require('./ReviewRouter')
const InventoryLogRouter = require('./InventoryLogRouter')

const routes = (app) => {
    app.use('/api/user', UserRouter)
    app.use('/api/product', ProductRouter)
    app.use('/api/type', TypeRouter)
    app.use('/api/bill', BillRouter)
    app.use('/api/cart', CartRouter)
    app.use('/api/wishlist', WishlistRouter)
    app.use('/api/service', ServiceRouter)
    app.use('/api/pet', PetRouter)
    app.use('/api/appointment', AppointmentRouter)
    app.use('/api/coupon', CouponRouter)
    app.use('/api/review', ReviewRouter)
    app.use('/api/inventory-log', InventoryLogRouter)
}
module.exports = routes
